version: '3.3'

services:

  labseq-sequence:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - test-labseq-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - test-labseq-network

volumes:
  redis_data:

networks:
  test-labseq-network:
    driver: bridge
